table manufacturer
	lineageTag: cfdc0118-3652-450f-9451-248798711414

	column Column1
		dataType: string
		lineageTag: b7309fbe-9a2f-4da5-8796-9b466f09a6af
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 7fe409b6-5a22-44b8-95d7-2ba20dd33da9
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 34cbe84c-810d-41a6-a896-685330b8fb75
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: ca639133-8b4e-47c5-8691-4afc529bcb36
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 202589fe-4cc6-47de-b789-d2dc040fe788
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: fae6db39-df78-4ac3-a8a1-d453ebadbad0
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 176f104f-6089-4820-b095-b4e33bd92ea9
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: d254592b-9645-4562-8bdd-33055bc71a29
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 6bc47778-f537-4dbd-8c89-22d43b1adc5d
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 4ed9beda-aa65-44bd-8ccf-33c95655dd31
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: ffd62700-ffe1-40fa-a845-1dc0b687a686
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 4caa39d8-e0dd-4a79-bfae-968f579d8ea3
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 0a0f42ee-088e-429b-b7ad-928269e4da8b
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 83d1ccfc-3326-4ce7-ad52-d9772218d2e2
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: ffbfe4c5-625e-44cf-9cfb-cc276ee1b6fa
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	partition manufacturer = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\DIAD\Data\USSales\bi_dimensions.xlsx"), null, true),
				    manufacturer_Sheet = Source{[Item="manufacturer",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(manufacturer_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Column1", type text}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

