table product
	lineageTag: 440e95f7-95ad-46d3-9551-903e55fbd13a

	column 'Product Details'
		dataType: string
		lineageTag: 952b2314-5dfd-4f62-912f-6a87d7471cd6
		summarizeBy: none
		sourceColumn: Product Details

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 9586b525-b4a8-414d-b568-dc35e37d2082
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 9b350c58-f2e8-47e4-be95-b3d289ce6547
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 7c77f05d-087f-45ac-81ce-685ba60c06dc
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 93940e16-f112-4cb9-bada-837346f302eb
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	partition product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\DIAD\Data\USSales\bi_dimensions.xlsx"), null, true),
				    product_Sheet = Source{[Item="product",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(product_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product Details", type any}, {"Column2", type text}, {"Column3", type text}, {"Column4", type any}, {"Column5", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

